site_name: Soda Description

markdown_extensions:
    - toc:
        baselevel: 2

theme:
    name: mkdocs
    highlightjs: true
    hljs_languages:
        - python
#    custom_dir: custom_theme/
        
markdown_extensions:
    - toc:
        permalink: true
        
extra_css: 
    - extra.css
    
nav:
    - Home: index.md
    - Donwload and Installation : Install.md
    - Board Configuration : BoardConfig.md
    - Desktop : Desktop.md
    - Connectivity : Connectivity.md
    - Development : Development.md
    - Utility : Utility.md
    - CLI Enviroment : Cli.md
    
highlightjs: true
hljs_languages: [python, cpp, java, javascript]
